version: '3.7'

services:
  ui:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app/
      - node_modules:/app/node_modules
    ports:
      - 3000:3000

  api:
    build: ./backend
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 80 --reload"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - 8000:80

volumes:
  node_modules: